name: mr_blue
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  flutter_phone_direct_caller: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
