name: mr_blue
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  http: ^1.3.0
  intl: ^0.20.2
  geolocator: ^13.0.4
  google_maps_flutter: ^2.12.1
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app_logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/intro_video.mp4
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
